// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegolem

import (
	"database/sql"
)

type Entity struct {
	Key                         string
	ExpiresAt                   int64
	Payload                     []byte
	CreatedAtBlock              int64
	LastModifiedAtBlock         int64
	Deleted                     bool
	TransactionIndexInBlock     int64
	OperationIndexInTransaction int64
	OwnerAddress                string
}

type NumericAnnotation struct {
	EntityKey                 string
	EntityLastModifiedAtBlock int64
	AnnotationKey             string
	Value                     int64
}

type ProcessingStatus struct {
	Network                  string
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

type SchemaVersion struct {
	ID       int64
	Entities sql.NullInt64
}

type StringAnnotation struct {
	EntityKey                 string
	EntityLastModifiedAtBlock int64
	AnnotationKey             string
	Value                     string
}
