// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlitegolem

import (
	"context"
)

const countNetworks = `-- name: CountNetworks :one
SELECT COUNT(DISTINCT network) FROM processing_status
`

func (q *Queries) CountNetworks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllEntities = `-- name: DeleteAllEntities :exec
DELETE FROM entities
`

func (q *Queries) DeleteAllEntities(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEntities)
	return err
}

const deleteAllNumericAnnotations = `-- name: DeleteAllNumericAnnotations :exec
DELETE FROM numeric_annotations
`

func (q *Queries) DeleteAllNumericAnnotations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllNumericAnnotations)
	return err
}

const deleteAllProcessingStatus = `-- name: DeleteAllProcessingStatus :exec
DELETE FROM processing_status
`

func (q *Queries) DeleteAllProcessingStatus(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProcessingStatus)
	return err
}

const deleteAllStringAnnotations = `-- name: DeleteAllStringAnnotations :exec
DELETE FROM string_annotations
`

func (q *Queries) DeleteAllStringAnnotations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllStringAnnotations)
	return err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entities WHERE key = ?
`

func (q *Queries) DeleteEntity(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteEntity, key)
	return err
}

const deleteNumericAnnotations = `-- name: DeleteNumericAnnotations :exec
DELETE FROM numeric_annotations WHERE entity_key = ?
`

func (q *Queries) DeleteNumericAnnotations(ctx context.Context, entityKey string) error {
	_, err := q.db.ExecContext(ctx, deleteNumericAnnotations, entityKey)
	return err
}

const deleteProcessingStatus = `-- name: DeleteProcessingStatus :exec
DELETE FROM processing_status WHERE network = ?
`

func (q *Queries) DeleteProcessingStatus(ctx context.Context, network string) error {
	_, err := q.db.ExecContext(ctx, deleteProcessingStatus, network)
	return err
}

const deleteStringAnnotations = `-- name: DeleteStringAnnotations :exec
DELETE FROM string_annotations WHERE entity_key = ?
`

func (q *Queries) DeleteStringAnnotations(ctx context.Context, entityKey string) error {
	_, err := q.db.ExecContext(ctx, deleteStringAnnotations, entityKey)
	return err
}

const entityExists = `-- name: EntityExists :one
SELECT COUNT(*) > 0 FROM entities WHERE key = ?
`

func (q *Queries) EntityExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, entityExists, key)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getEntitiesByOwner = `-- name: GetEntitiesByOwner :many
SELECT key, expires_at, payload FROM entities WHERE owner_address = ?
`

type GetEntitiesByOwnerRow struct {
	Key       string
	ExpiresAt int64
	Payload   []byte
}

func (q *Queries) GetEntitiesByOwner(ctx context.Context, ownerAddress string) ([]GetEntitiesByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntitiesByOwner, ownerAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntitiesByOwnerRow
	for rows.Next() {
		var i GetEntitiesByOwnerRow
		if err := rows.Scan(&i.Key, &i.ExpiresAt, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntity = `-- name: GetEntity :one
SELECT expires_at, payload, owner_address FROM entities WHERE key = ?
`

type GetEntityRow struct {
	ExpiresAt    int64
	Payload      []byte
	OwnerAddress string
}

func (q *Queries) GetEntity(ctx context.Context, key string) (GetEntityRow, error) {
	row := q.db.QueryRowContext(ctx, getEntity, key)
	var i GetEntityRow
	err := row.Scan(&i.ExpiresAt, &i.Payload, &i.OwnerAddress)
	return i, err
}

const getNumericAnnotations = `-- name: GetNumericAnnotations :many
SELECT annotation_key, value FROM numeric_annotations WHERE entity_key = ?
`

type GetNumericAnnotationsRow struct {
	AnnotationKey string
	Value         int64
}

func (q *Queries) GetNumericAnnotations(ctx context.Context, entityKey string) ([]GetNumericAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNumericAnnotations, entityKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNumericAnnotationsRow
	for rows.Next() {
		var i GetNumericAnnotationsRow
		if err := rows.Scan(&i.AnnotationKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingStatus = `-- name: GetProcessingStatus :one
SELECT last_processed_block_number, last_processed_block_hash FROM processing_status WHERE network = ?
`

type GetProcessingStatusRow struct {
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

func (q *Queries) GetProcessingStatus(ctx context.Context, network string) (GetProcessingStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getProcessingStatus, network)
	var i GetProcessingStatusRow
	err := row.Scan(&i.LastProcessedBlockNumber, &i.LastProcessedBlockHash)
	return i, err
}

const getStringAnnotations = `-- name: GetStringAnnotations :many
SELECT annotation_key, value FROM string_annotations WHERE entity_key = ?
`

type GetStringAnnotationsRow struct {
	AnnotationKey string
	Value         string
}

func (q *Queries) GetStringAnnotations(ctx context.Context, entityKey string) ([]GetStringAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStringAnnotations, entityKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStringAnnotationsRow
	for rows.Next() {
		var i GetStringAnnotationsRow
		if err := rows.Scan(&i.AnnotationKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasProcessingStatus = `-- name: HasProcessingStatus :one
SELECT COUNT(*) > 0 FROM processing_status WHERE network = ?
`

func (q *Queries) HasProcessingStatus(ctx context.Context, network string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasProcessingStatus, network)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertEntity = `-- name: InsertEntity :exec
INSERT INTO entities (key, expires_at, payload, owner_address) VALUES (?, ?, ?, ?)
`

type InsertEntityParams struct {
	Key          string
	ExpiresAt    int64
	Payload      []byte
	OwnerAddress string
}

func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) error {
	_, err := q.db.ExecContext(ctx, insertEntity,
		arg.Key,
		arg.ExpiresAt,
		arg.Payload,
		arg.OwnerAddress,
	)
	return err
}

const insertNumericAnnotation = `-- name: InsertNumericAnnotation :exec
INSERT INTO numeric_annotations (entity_key, annotation_key, value) VALUES (?, ?, ?)
`

type InsertNumericAnnotationParams struct {
	EntityKey     string
	AnnotationKey string
	Value         int64
}

func (q *Queries) InsertNumericAnnotation(ctx context.Context, arg InsertNumericAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertNumericAnnotation, arg.EntityKey, arg.AnnotationKey, arg.Value)
	return err
}

const insertProcessingStatus = `-- name: InsertProcessingStatus :exec
INSERT INTO processing_status (network, last_processed_block_number, last_processed_block_hash) VALUES (?, ?, ?)
`

type InsertProcessingStatusParams struct {
	Network                  string
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

func (q *Queries) InsertProcessingStatus(ctx context.Context, arg InsertProcessingStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertProcessingStatus, arg.Network, arg.LastProcessedBlockNumber, arg.LastProcessedBlockHash)
	return err
}

const insertStringAnnotation = `-- name: InsertStringAnnotation :exec
INSERT INTO string_annotations (entity_key, annotation_key, value) VALUES (?, ?, ?)
`

type InsertStringAnnotationParams struct {
	EntityKey     string
	AnnotationKey string
	Value         string
}

func (q *Queries) InsertStringAnnotation(ctx context.Context, arg InsertStringAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertStringAnnotation, arg.EntityKey, arg.AnnotationKey, arg.Value)
	return err
}

const numericAnnotationsForEntityExists = `-- name: NumericAnnotationsForEntityExists :one
SELECT COUNT(*) > 0 FROM numeric_annotations WHERE entity_key = ?
`

func (q *Queries) NumericAnnotationsForEntityExists(ctx context.Context, entityKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, numericAnnotationsForEntityExists, entityKey)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const stringAnnotationsForEntityExists = `-- name: StringAnnotationsForEntityExists :one
SELECT COUNT(*) > 0 FROM string_annotations WHERE entity_key = ?
`

func (q *Queries) StringAnnotationsForEntityExists(ctx context.Context, entityKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, stringAnnotationsForEntityExists, entityKey)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateEntityExpiresAt = `-- name: UpdateEntityExpiresAt :exec
UPDATE entities SET expires_at = ? WHERE key = ?
`

type UpdateEntityExpiresAtParams struct {
	ExpiresAt int64
	Key       string
}

func (q *Queries) UpdateEntityExpiresAt(ctx context.Context, arg UpdateEntityExpiresAtParams) error {
	_, err := q.db.ExecContext(ctx, updateEntityExpiresAt, arg.ExpiresAt, arg.Key)
	return err
}

const updateProcessingStatus = `-- name: UpdateProcessingStatus :exec
UPDATE processing_status SET last_processed_block_number = ?, last_processed_block_hash = ? WHERE network = ?
`

type UpdateProcessingStatusParams struct {
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
	Network                  string
}

func (q *Queries) UpdateProcessingStatus(ctx context.Context, arg UpdateProcessingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingStatus, arg.LastProcessedBlockNumber, arg.LastProcessedBlockHash, arg.Network)
	return err
}
