// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitegolem

import (
	"context"
)

type Querier interface {
	DeleteEntity(ctx context.Context, key string) error
	DeleteNumericAnnotations(ctx context.Context, entityKey string) error
	DeleteProcessingStatus(ctx context.Context, network string) error
	DeleteStringAnnotations(ctx context.Context, entityKey string) error
	EntityExists(ctx context.Context, key string) (bool, error)
	GetEntity(ctx context.Context, key string) (GetEntityRow, error)
	GetNumericAnnotations(ctx context.Context, entityKey string) ([]GetNumericAnnotationsRow, error)
	GetProcessingStatus(ctx context.Context, network string) (GetProcessingStatusRow, error)
	GetStringAnnotations(ctx context.Context, entityKey string) ([]GetStringAnnotationsRow, error)
	HasProcessingStatus(ctx context.Context, network string) (bool, error)
	InsertEntity(ctx context.Context, arg InsertEntityParams) error
	InsertNumericAnnotation(ctx context.Context, arg InsertNumericAnnotationParams) error
	InsertProcessingStatus(ctx context.Context, arg InsertProcessingStatusParams) error
	InsertStringAnnotation(ctx context.Context, arg InsertStringAnnotationParams) error
	NumericAnnotationsForEntityExists(ctx context.Context, entityKey string) (bool, error)
	StringAnnotationsForEntityExists(ctx context.Context, entityKey string) (bool, error)
	UpdateProcessingStatus(ctx context.Context, arg UpdateProcessingStatusParams) error
}

var _ Querier = (*Queries)(nil)
