// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlitegolem

import (
	"context"
)

const countNetworks = `-- name: CountNetworks :one
SELECT COUNT(DISTINCT network) FROM processing_status
`

func (q *Queries) CountNetworks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllEntities = `-- name: DeleteAllEntities :exec
DELETE FROM entities
`

func (q *Queries) DeleteAllEntities(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEntities)
	return err
}

const deleteAllNumericAnnotations = `-- name: DeleteAllNumericAnnotations :exec
DELETE FROM numeric_annotations
`

func (q *Queries) DeleteAllNumericAnnotations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllNumericAnnotations)
	return err
}

const deleteAllProcessingStatus = `-- name: DeleteAllProcessingStatus :exec
DELETE FROM processing_status
`

func (q *Queries) DeleteAllProcessingStatus(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProcessingStatus)
	return err
}

const deleteAllStringAnnotations = `-- name: DeleteAllStringAnnotations :exec
DELETE FROM string_annotations
`

func (q *Queries) DeleteAllStringAnnotations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllStringAnnotations)
	return err
}

const deleteEntitiesUntilBlock = `-- name: DeleteEntitiesUntilBlock :exec
DELETE FROM entities AS e
WHERE e.last_modified_at_block <= ?1
AND (
  EXISTS (
    SELECT 1
    FROM entities AS e2
    WHERE e2.key = e.key
    AND e2.last_modified_at_block > e.last_modified_at_block
  )
  OR e.deleted = TRUE
)
`

func (q *Queries) DeleteEntitiesUntilBlock(ctx context.Context, block int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntitiesUntilBlock, block)
	return err
}

const deleteEntity = `-- name: DeleteEntity :exec
INSERT INTO entities (
  key, expires_at, payload, content_type, owner_address,
  created_at_block, last_modified_at_block, deleted,
  transaction_index_in_block, operation_index_in_transaction
)
SELECT
    e.key,
    e.expires_at,
    e.payload,
    e.content_type,
    e.owner_address,
    e.created_at_block,
    ?1 AS last_modified_at_block,
    TRUE AS deleted,
    ?2 AS transaction_index_in_block,
    ?3 AS operation_index_in_transaction
FROM entities AS e
WHERE e.key = ?4
AND e.deleted = FALSE
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
)
`

type DeleteEntityParams struct {
	LastModifiedAtBlock         int64
	TransactionIndexInBlock     int64
	OperationIndexInTransaction int64
	Key                         string
}

func (q *Queries) DeleteEntity(ctx context.Context, arg DeleteEntityParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntity,
		arg.LastModifiedAtBlock,
		arg.TransactionIndexInBlock,
		arg.OperationIndexInTransaction,
		arg.Key,
	)
	return err
}

const deleteNumericAnnotationsUntilBlock = `-- name: DeleteNumericAnnotationsUntilBlock :exec
DELETE FROM numeric_annotations AS a
WHERE a.entity_last_modified_at_block <= ?1
AND (
  EXISTS (
    SELECT 1
    FROM entities AS e
    WHERE e.key = a.entity_key
    AND (
      -- either there is a more recent version of the entity that this annotation
      -- belongs to
      e.last_modified_at_block > a.entity_last_modified_at_block
      -- or the entity that this annotation belongs to has been deleted
      OR (
        e.last_modified_at_block = a.entity_last_modified_at_block
        AND e.deleted = TRUE
      )
    )
  )
)
`

func (q *Queries) DeleteNumericAnnotationsUntilBlock(ctx context.Context, block int64) error {
	_, err := q.db.ExecContext(ctx, deleteNumericAnnotationsUntilBlock, block)
	return err
}

const deleteProcessingStatus = `-- name: DeleteProcessingStatus :exec
DELETE FROM processing_status WHERE network = ?
`

func (q *Queries) DeleteProcessingStatus(ctx context.Context, network string) error {
	_, err := q.db.ExecContext(ctx, deleteProcessingStatus, network)
	return err
}

const deleteStringAnnotationsUntilBlock = `-- name: DeleteStringAnnotationsUntilBlock :exec
DELETE FROM string_annotations AS a
WHERE a.entity_last_modified_at_block <= ?1
AND (
  EXISTS (
    SELECT 1
    FROM entities AS e
    WHERE e.key = a.entity_key
    AND (
      -- either there is a more recent version of the entity that this annotation
      -- belongs to
      e.last_modified_at_block > a.entity_last_modified_at_block
      -- or the entity that this annotation belongs to has been deleted
      OR (
        e.last_modified_at_block = a.entity_last_modified_at_block
        AND e.deleted = TRUE
      )
    )
  )
)
`

func (q *Queries) DeleteStringAnnotationsUntilBlock(ctx context.Context, block int64) error {
	_, err := q.db.ExecContext(ctx, deleteStringAnnotationsUntilBlock, block)
	return err
}

const getAllEntityKeys = `-- name: GetAllEntityKeys :many
SELECT key
FROM entities AS e
WHERE e.deleted = FALSE
AND e.last_modified_at_block <= ?1
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
  AND e2.last_modified_at_block <= ?1
)
ORDER BY key
`

func (q *Queries) GetAllEntityKeys(ctx context.Context, block int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntityKeys, block)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntity = `-- name: GetEntity :one
SELECT e1.expires_at, e1.payload, e1.owner_address, e1.created_at_block, e1.last_modified_at_block
FROM entities AS e1
WHERE e1.key = ?1
AND e1.deleted = FALSE
AND e1.last_modified_at_block <= ?2
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e1.key
  AND e2.last_modified_at_block > e1.last_modified_at_block
  -- There is a bug in sqlc currently with repeated named args,
  -- so we resolve the named arg ourselves here.
  -- See https://github.com/sqlc-dev/sqlc/issues/4110
  AND e2.last_modified_at_block <= ?2
)
`

type GetEntityParams struct {
	Key   string
	Block int64
}

type GetEntityRow struct {
	ExpiresAt           int64
	Payload             []byte
	OwnerAddress        string
	CreatedAtBlock      int64
	LastModifiedAtBlock int64
}

func (q *Queries) GetEntity(ctx context.Context, arg GetEntityParams) (GetEntityRow, error) {
	row := q.db.QueryRowContext(ctx, getEntity, arg.Key, arg.Block)
	var i GetEntityRow
	err := row.Scan(
		&i.ExpiresAt,
		&i.Payload,
		&i.OwnerAddress,
		&i.CreatedAtBlock,
		&i.LastModifiedAtBlock,
	)
	return i, err
}

const getEntityCount = `-- name: GetEntityCount :one
SELECT COUNT(*)
FROM entities AS e
WHERE e.deleted = FALSE
AND e.last_modified_at_block <= ?1
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
  AND e2.last_modified_at_block <= ?1
)
`

func (q *Queries) GetEntityCount(ctx context.Context, block int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEntityCount, block)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNumericAnnotations = `-- name: GetNumericAnnotations :many
SELECT a.annotation_key, a.value
FROM numeric_annotations AS a INNER JOIN entities AS e
  ON a.entity_key = e.key
AND a.entity_last_modified_at_block = e.last_modified_at_block
AND e.deleted = FALSE
AND e.last_modified_at_block <= ?2
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
  AND e2.last_modified_at_block <= ?2
)
WHERE a.entity_key = ?1
`

type GetNumericAnnotationsParams struct {
	EntityKey string
	Block     int64
}

type GetNumericAnnotationsRow struct {
	AnnotationKey string
	Value         int64
}

func (q *Queries) GetNumericAnnotations(ctx context.Context, arg GetNumericAnnotationsParams) ([]GetNumericAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNumericAnnotations, arg.EntityKey, arg.Block)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNumericAnnotationsRow
	for rows.Next() {
		var i GetNumericAnnotationsRow
		if err := rows.Scan(&i.AnnotationKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingStatus = `-- name: GetProcessingStatus :one
SELECT last_processed_block_number, last_processed_block_hash FROM processing_status WHERE network = ?
`

type GetProcessingStatusRow struct {
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

func (q *Queries) GetProcessingStatus(ctx context.Context, network string) (GetProcessingStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getProcessingStatus, network)
	var i GetProcessingStatusRow
	err := row.Scan(&i.LastProcessedBlockNumber, &i.LastProcessedBlockHash)
	return i, err
}

const getStringAnnotations = `-- name: GetStringAnnotations :many
SELECT a.annotation_key, a.value
FROM string_annotations AS a INNER JOIN entities AS e
  ON a.entity_key = e.key
AND a.entity_last_modified_at_block = e.last_modified_at_block
AND e.deleted = FALSE
AND e.last_modified_at_block <= ?2
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
  AND e2.last_modified_at_block <= ?2
)
WHERE a.entity_key = ?1
`

type GetStringAnnotationsParams struct {
	EntityKey string
	Block     int64
}

type GetStringAnnotationsRow struct {
	AnnotationKey string
	Value         string
}

func (q *Queries) GetStringAnnotations(ctx context.Context, arg GetStringAnnotationsParams) ([]GetStringAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStringAnnotations, arg.EntityKey, arg.Block)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStringAnnotationsRow
	for rows.Next() {
		var i GetStringAnnotationsRow
		if err := rows.Scan(&i.AnnotationKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasProcessingStatus = `-- name: HasProcessingStatus :one
SELECT COUNT(*) > 0 FROM processing_status WHERE network = ?
`

func (q *Queries) HasProcessingStatus(ctx context.Context, network string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasProcessingStatus, network)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertEntity = `-- name: InsertEntity :exec
INSERT INTO entities (
  key, expires_at, payload, content_type, owner_address,
  created_at_block, last_modified_at_block, deleted,
  transaction_index_in_block, operation_index_in_transaction
)
VALUES (
  ?, ?, ?, ?, ?,
  ?, ?, ?,
  ?, ?
)
`

type InsertEntityParams struct {
	Key                         string
	ExpiresAt                   int64
	Payload                     []byte
	ContentType                 string
	OwnerAddress                string
	CreatedAtBlock              int64
	LastModifiedAtBlock         int64
	Deleted                     bool
	TransactionIndexInBlock     int64
	OperationIndexInTransaction int64
}

func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) error {
	_, err := q.db.ExecContext(ctx, insertEntity,
		arg.Key,
		arg.ExpiresAt,
		arg.Payload,
		arg.ContentType,
		arg.OwnerAddress,
		arg.CreatedAtBlock,
		arg.LastModifiedAtBlock,
		arg.Deleted,
		arg.TransactionIndexInBlock,
		arg.OperationIndexInTransaction,
	)
	return err
}

const insertNumericAnnotation = `-- name: InsertNumericAnnotation :exec
INSERT INTO numeric_annotations (
  entity_key, entity_last_modified_at_block,  annotation_key, value
) VALUES (
  ?, ?, ?, ?
)
`

type InsertNumericAnnotationParams struct {
	EntityKey                 string
	EntityLastModifiedAtBlock int64
	AnnotationKey             string
	Value                     int64
}

func (q *Queries) InsertNumericAnnotation(ctx context.Context, arg InsertNumericAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertNumericAnnotation,
		arg.EntityKey,
		arg.EntityLastModifiedAtBlock,
		arg.AnnotationKey,
		arg.Value,
	)
	return err
}

const insertProcessingStatus = `-- name: InsertProcessingStatus :exec
INSERT INTO processing_status (network, last_processed_block_number, last_processed_block_hash) VALUES (?, ?, ?)
`

type InsertProcessingStatusParams struct {
	Network                  string
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

func (q *Queries) InsertProcessingStatus(ctx context.Context, arg InsertProcessingStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertProcessingStatus, arg.Network, arg.LastProcessedBlockNumber, arg.LastProcessedBlockHash)
	return err
}

const insertStringAnnotation = `-- name: InsertStringAnnotation :exec
INSERT INTO string_annotations (
  entity_key, entity_last_modified_at_block,  annotation_key, value
) VALUES (
  ?, ?, ?, ?
)
`

type InsertStringAnnotationParams struct {
	EntityKey                 string
	EntityLastModifiedAtBlock int64
	AnnotationKey             string
	Value                     string
}

func (q *Queries) InsertStringAnnotation(ctx context.Context, arg InsertStringAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertStringAnnotation,
		arg.EntityKey,
		arg.EntityLastModifiedAtBlock,
		arg.AnnotationKey,
		arg.Value,
	)
	return err
}

const updateEntityExpiresAt = `-- name: UpdateEntityExpiresAt :exec
INSERT INTO entities (
  key, expires_at, payload, content_type, owner_address,
  created_at_block, last_modified_at_block, deleted,
  transaction_index_in_block, operation_index_in_transaction
)
SELECT
    e.key,
    ?1 AS expires_at,
    e.payload,
    e.content_type,
    e.owner_address,
    e.created_at_block,
    ?2 AS last_modified_at_block,
    e.deleted,
    ?3 AS transaction_index_in_block,
    ?4 AS operation_index_in_transaction
FROM entities AS e
WHERE e.key = ?5
AND e.deleted = FALSE
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
)
`

type UpdateEntityExpiresAtParams struct {
	ExpiresAt                   int64
	LastModifiedAtBlock         int64
	TransactionIndexInBlock     int64
	OperationIndexInTransaction int64
	Key                         string
}

func (q *Queries) UpdateEntityExpiresAt(ctx context.Context, arg UpdateEntityExpiresAtParams) error {
	_, err := q.db.ExecContext(ctx, updateEntityExpiresAt,
		arg.ExpiresAt,
		arg.LastModifiedAtBlock,
		arg.TransactionIndexInBlock,
		arg.OperationIndexInTransaction,
		arg.Key,
	)
	return err
}

const updateEntityOwner = `-- name: UpdateEntityOwner :exec
INSERT INTO entities (
  key, expires_at, payload, content_type, owner_address,
  created_at_block, last_modified_at_block, deleted,
  transaction_index_in_block, operation_index_in_transaction
)
SELECT
    e.key,
    e.expires_at,
    e.payload,
    e.content_type,
    ?1,
    e.created_at_block,
    ?2 AS last_modified_at_block,
    e.deleted,
    ?3 AS transaction_index_in_block,
    ?4 AS operation_index_in_transaction
FROM entities AS e
WHERE e.key = ?5
AND e.deleted = FALSE
AND NOT EXISTS (
  SELECT 1
  FROM entities AS e2
  WHERE e2.key = e.key
  AND e2.last_modified_at_block > e.last_modified_at_block
)
`

type UpdateEntityOwnerParams struct {
	OwnerAddress                string
	LastModifiedAtBlock         int64
	TransactionIndexInBlock     int64
	OperationIndexInTransaction int64
	Key                         string
}

func (q *Queries) UpdateEntityOwner(ctx context.Context, arg UpdateEntityOwnerParams) error {
	_, err := q.db.ExecContext(ctx, updateEntityOwner,
		arg.OwnerAddress,
		arg.LastModifiedAtBlock,
		arg.TransactionIndexInBlock,
		arg.OperationIndexInTransaction,
		arg.Key,
	)
	return err
}

const updateProcessingStatus = `-- name: UpdateProcessingStatus :exec
UPDATE processing_status SET last_processed_block_number = ?, last_processed_block_hash = ? WHERE network = ?
`

type UpdateProcessingStatusParams struct {
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
	Network                  string
}

func (q *Queries) UpdateProcessingStatus(ctx context.Context, arg UpdateProcessingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingStatus, arg.LastProcessedBlockNumber, arg.LastProcessedBlockHash, arg.Network)
	return err
}
