// Code generated by rlpgen. DO NOT EDIT.

package storagetx

import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *ArkivTransaction) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, _tmp2 := range obj.Create {
		_tmp3 := w.List()
		w.WriteUint64(_tmp2.BTL)
		w.WriteString(_tmp2.ContentType)
		w.WriteBytes(_tmp2.Payload)
		_tmp4 := w.List()
		for _, _tmp5 := range _tmp2.StringAnnotations {
			_tmp6 := w.List()
			w.WriteString(_tmp5.Key)
			w.WriteString(_tmp5.Value)
			w.ListEnd(_tmp6)
		}
		w.ListEnd(_tmp4)
		_tmp7 := w.List()
		for _, _tmp8 := range _tmp2.NumericAnnotations {
			_tmp9 := w.List()
			w.WriteString(_tmp8.Key)
			w.WriteUint64(_tmp8.Value)
			w.ListEnd(_tmp9)
		}
		w.ListEnd(_tmp7)
		w.ListEnd(_tmp3)
	}
	w.ListEnd(_tmp1)
	_tmp10 := w.List()
	for _, _tmp11 := range obj.Update {
		_tmp12 := w.List()
		w.WriteBytes(_tmp11.EntityKey[:])
		w.WriteString(_tmp11.ContentType)
		w.WriteUint64(_tmp11.BTL)
		w.WriteBytes(_tmp11.Payload)
		_tmp13 := w.List()
		for _, _tmp14 := range _tmp11.StringAnnotations {
			_tmp15 := w.List()
			w.WriteString(_tmp14.Key)
			w.WriteString(_tmp14.Value)
			w.ListEnd(_tmp15)
		}
		w.ListEnd(_tmp13)
		_tmp16 := w.List()
		for _, _tmp17 := range _tmp11.NumericAnnotations {
			_tmp18 := w.List()
			w.WriteString(_tmp17.Key)
			w.WriteUint64(_tmp17.Value)
			w.ListEnd(_tmp18)
		}
		w.ListEnd(_tmp16)
		w.ListEnd(_tmp12)
	}
	w.ListEnd(_tmp10)
	_tmp19 := w.List()
	for _, _tmp20 := range obj.Delete {
		w.WriteBytes(_tmp20[:])
	}
	w.ListEnd(_tmp19)
	_tmp21 := w.List()
	for _, _tmp22 := range obj.Extend {
		_tmp23 := w.List()
		w.WriteBytes(_tmp22.EntityKey[:])
		w.WriteUint64(_tmp22.NumberOfBlocks)
		w.ListEnd(_tmp23)
	}
	w.ListEnd(_tmp21)
	_tmp24 := w.List()
	for _, _tmp25 := range obj.ChangeOwner {
		_tmp26 := w.List()
		w.WriteBytes(_tmp25.EntityKey[:])
		w.WriteBytes(_tmp25.NewOwner[:])
		w.ListEnd(_tmp26)
	}
	w.ListEnd(_tmp24)
	w.ListEnd(_tmp0)
	return w.Flush()
}
